### ISSUE TITLE
[Bug]: Dead player spectating a open world boss fight, experiences missing textures and low poly enviroment when the alive player attempts to revive at a grace far away.

### ISSUE THREAD

**Issue by swolewizard** [LukeYui/EldenRingSeamlessCoopRelease#104]
### Discord Username

Huntardy#2566

### Describe the issue in detail

When a player dies during a open world boss fight and is stuck spectating the remaining guest player, then that player manages to kill the boss and they need to find a grace to revive the dead spectating player, if the grace is too far away the entire world & textures for the spectating player are in incredibly low detail and no mobs / grace sites render, all gets fixed when the spectated player rests to revive the player, but it's a little weird.

### Steps to recreate the bug

Die to a boss with a friend connected together, have the friend kill the open world boss then attempt to revive them at a grace incredibly far away, the spectating player should experience what I described.

### Version

1.1.0

**Comment by LukeYui** [comment]
Hi, thanks for the report. This is not a bug, it's just because the dead player's body doesn't move from their current position and therefore none of the other game chunks are loaded.

In the future I might add proximity to the spectator cam, however for now it's like this to save resources and run the game smoothly.
