### ISSUE TITLE
[Bug]: godrick agro on dead players

### ISSUE THREAD

**Issue by madmaxx11** [LukeYui/EldenRingSeamlessCoopRelease#178]
### Discord Username

madmaxxxx #8479

### Describe the issue in detail

godrick will agro on a dead player and just stand there and not fight back only had this happen with godrick happen every time one of us diedto 

### Steps to recreate the bug

i don't remember the host dying to try with people that connect 

### Version

1.2.4 (Latest)

**Comment by JanAppold** [comment]
Yes same here it is basically on every boss. Might be even every enemy type. 

To Reproduce:
Fight against any greater enemy in coop. 
Let one die
Might still aggro the alive player but as soon as he would switch aggro he switches to the dead person and just stands there. 
It is possible to get the aggro back ( i think its when you done enough damage which would also normally trigger a aggro switch)

**Comment by Zenoo** [comment]
Same here, everytime one player dies, he gets the aggro after, forever.

**Comment by Zenoo** [comment]
Every boss we tested had this issue (or at least those one of us died on, so the harder ones)

**Comment by madmaxx11** [comment]
i have only experienced it with significant ones

**Comment by zaylivinglive** [comment]
I have this same issue. I have not experienced this bug on any other random world bosses or enemies though, only Godrick. We did not have this issue with Margit, however we were on the first version of the mod then. Note we have not attempted fighting any other named bosses past Godrick, so i am not sure if the bug stops there or persits onwards. 

In greater detail, While fighting Godrick, halfway through the boss fight it was very apparent he was not recognizing my Co-op partner. He was only agro'd on me, the host, and the entire fight while im dodging him my partner is fighting him and chipping his health down with no switch of agro. When I died, my bug was a bit different. While he did not attack my dead body, Godrick froze as if having no enemy, even though my Co-op partner was alive and well. When attacking Godrick, He would turn to where the damage was coming from, but not move from his fixed location or ever return attacking, until he was killed. I may have a video of this if it helps.

**Comment by micahsnyder** [comment]
I observed the agro-on-dead-players behavior with Morgott in Leyndell, Royal Capital.  Morgott continued to focus on a recently killed player until attacked, and sometimes turned attention back to that dead during the fight.

**Comment by SirDifferential** [comment]
We saw this especially with Godrick, but the Evergaol bosses and Tree Sentinel AIs didn't break on a player's death. I don't think this happened with Margit with our group of 4 players.

**Comment by orreonline** [comment]
Just done an all remembrances playthrough with 3 ppl, started on 1.2.4 and finished it yesterday on 1.2.5.
We had this happen repeatedly in both versions on: Malenia, Godrick, Hoarah Loux, Astel, Mohg.
Host or wanderer dies and boss will freeze around the death spot and only move to do special attacks sometimes when surviving players stay close to them for extended periods. If they're not in this state they often swap aggro to the dead player during fights. They can leave the frozen state, and reenter it when close to a death spot. So our guess is it happens when they have aggro on a dead player.
Most other bosses we didnt die on, so couldnt say how many more are affected.
We would start a new seamless run right now but for this issue, it kills the fun of the runs really when the bosses just fold after a player death. And it happens so very often, probably had it happen 30-ish times in our 13h playthrough.

Also cheers for all the hard work on this excellent mod, very much apprecieted.

/
orreonline#0149 on discord
