### ISSUE TITLE
[Bug]: Host using Microsoft Powertoys cannot join game

### ISSUE THREAD

**Issue by Wilhelmeting** [LukeYui/EldenRingSeamlessCoopRelease#201]
### Discord Username

Wilhelm#0833

### Describe the issue in detail

My friend has an unorthodox keyboard setup so he uses microsoft powertoys for the hotkeys to play elden ring,
When he has powertoys active i cannot join his game until he turns it off. He can activate it after ive joined.

Not a huge issue but quite annoying.
When he opens a world with powertoys active i he cannot simply turn it off and im able to join.
He has to turn off powertoys leave the world, start a new world, leave that world and then start a new world.

### Steps to recreate the bug

Joining game with host using powertoys

### Version

1.2.4 (Latest)

**Comment by Neofaucheur** [comment]
I have Powertoys running in the background myself, but it doesn't seem to cause issue with hosting. I only joined someone else once so that might be inconclusive but it worked too.
That being said, Powertoys is in version 0.59.1, doesn't run as admin, and "Awake" and "Keyboard Manager" are turned off (everything else is on).

**Comment by Wilhelmeting** [comment]
Okay thank you for the info. We will check our settings!
