### ISSUE TITLE
[Bug]: Host gaining bell bearings and NPC quests progression from clients

### ISSUE THREAD

**Issue by Rieyori** [LukeYui/EldenRingSeamlessCoopRelease#221]
### Discord Username

Rie#9001

### Describe the issue in detail

Issue : Host getting NPC quest progression and twin maiden shop items unlock from clients [1.05]

I joined into a session where the host was on a fresh save, created a few minutes prior to starting our squad in Discord.
My character is on NG+1 with all items in the twin maiden husk unlocked, all NPC quests completed,
After I joined in, the host later discovered that he had all the items unlocked in his twin maiden husk shop.
Worst, certain Limgrave NPC quest progression seems to carry over from my save to his.
Rodericka was transferred to the Roundtable Hold prior to him even reaching Stormhill Shack.
Alexander the Warrior Great Jar was gone even though we haven't talked to the NPC on this session.

### Steps to recreate the bug

To verify if the issue is not just from my end, I took turns with other players in my squad and start a new character.
I either host the game or let someone else with another new character host. Then, we let another squad mate connect to the session using characters with higher progression.

The result seems consistent, me and another players with new characters gain access to all the new upgrade materials even on our first visit to the roundtable hold.
Alexander also disappeared from Limgrave area, even though we have never left Limgrave nor talked to him ever.

### Version

1.2.4 (Latest)

**Comment by mwmuni** [comment]
This seems related to the bugs surrounding character progression in general. Such as roundtable hold contantly resetting, or Melina talking to the player who didn't teleport to roundtable hold the first time the join the host every time.

It seems to be an issue with how the game state updates using a concensus model, sharing world states between clients, which usually ignores NPC states due to the summon flag being set. I don't believe there's an easy fix for this that doesn't totally break parallel progression.
