### ISSUE TITLE
[Bug]: After Port coop partner will be disconnected

### ISSUE THREAD

**Issue by Rubyurek** [LukeYui/EldenRingSeamlessCoopRelease#356]
### Discord Username

Rubyurek#8433

### Describe the issue in detail

With the latest update I noticed that sometimes after a port the partner gets disconnected for no reason.

### Steps to recreate the bug

- Coop with someone
- Port in some bonefire

### Version

1.2.5 (Latest)

**Comment by CrazyPotatoes** [comment]
Yeah I get this very frequently.

On party wipe and respawn, the client gets kicked ~95% of the time. 
When returning from evergaols, invasions, or using the exit teleporter of dungeons, disconnection 75% of the time.
On fast travel to site of grace on map, using a teleport chest, or waygate, client disconnects 25% of the time.

Doesn't seem to matter if I host or she hosts and I have no idea if it's because of a software desync, table collision (memory management), difference in loading times, framerate, or what. Once the disconnection happens, the only way back in is for the host to mist out and recreate. Attempting to rejoin without doing that results in joining player messages and timeout without ever getting to the joining as wanderer stage.
