### ISSUE TITLE
[Bug]: NPC reset

### ISSUE THREAD

**Issue by YantowCrayz** [LukeYui/EldenRingSeamlessCoopRelease#381]
### Discord Username

Gengar#3599

### Describe the issue in detail

All npcs when i join someone’s world forget about me entirely and do not keep in the same spot. The spirit tuner has completely vanished for me and is no longer in their world for me and keeps me from getting her hood.

### Steps to recreate the bug

Join other players world and talk to any npc, their diolog will be as if they never met you.

### Version

1.2.5 (Latest)

**Comment by adonisd** [comment]
same thing is happening to me. when i join someone it's like am meeting the npcs for the first time. same thing is happening with my coop partner when they join my game. (for them it's like they are meeting the npcs for the first time).

This started happening with 1.3.0 for me right after the event where u get invaded by someone in roundtable hold and u get their armor in the end. my friend was host they got invaded on my side the roundtable hold was just fine.  since then this bug is here
