### ISSUE TITLE
[Bug]: Greyoll died while fighting Godskin Apostle in Caelid Tower

### ISSUE THREAD

**Issue by dcenygma** [LukeYui/EldenRingSeamlessCoopRelease#474]
### Discord Username

DCEnygma#5871

### Describe the issue in detail

While fighting the Godskin Apostle in the bottom of the Caelid tower, suddenly received about 50000 runes and 5 dragon hearts (confirmed later that Greyoll died).

### Steps to recreate the bug

Fighting Godskin Apostle (2 player co-op) in bottom of Caelid tower while Greyoll is still alive, unsure what else would need to be done.

### Version

1.4.3 (Latest)

**Comment by NightUndead** [comment]
This happened to me and a friend right as we respawned after having died to the Putrid Avatar near Fort Faroth.

**Comment by alexander-novo** [comment]
It seems if you get anywhere near greyoll, she'll just die.

**Comment by Zerahn** [comment]
This happened to me and some friends twice now. The first we got teleported to the Sellia Crystal Tunnel via the trapped chest in the Dragonburnt Ruins. I'm not exactly sure when it happened but at some point as we were leaving the tunnel my game froze for like 10 seconds (friend was hosting, no freeze for him) and as he was shouting "where'd all these runes come from?!" my game unfroze and I noticed I was also rich and had a bunch of dragon hearts.

The second time we were farming the weakened dragons near Greyoll and had been doing so for about half an hour. For some reason after one rest at the nearby Faroth grace site the first two little ones got one-shot.  (The third we fought normally). Suddenly Greyoll took a bunch more damage, I don't even know why, so a guy who just died (not the host) panic-rested to reset it - then the same friend was like "I'm gonna level!" as we were fighting the first little dragon, and as the other two (me and host) broke off and went back toward the grace Greyoll respawned and then immediately died for no reason.

I wish I had more insight as to what would cause this. If it helps, we only got 80k runes for Greyoll's death and none for any of the little ones, so it probably wasn't due to the little ones dying en masse - it was specifically Greyoll taking unexplained damage.
