### ISSUE TITLE
[Bug]: can’t use spirt ashes summons

### ISSUE THREAD

**Issue by Xyzcraw** [LukeYui/EldenRingSeamlessCoopRelease#478]
### Describe the issue in detail

I can’t use spirit ashes.  I used to be able to use them normally but I can’t anymore. This stated in the version before 1.4.3 but seems to still be happening in 1.4.3. It dose not matter if I’m playing solo or with friends. Thanks for the help

### Steps to recreate the bug

Not sure how to recreate this it happened randomly it seems

### Version

1.4.3 (Latest)

**Comment by Muramas** [comment]
I am able to use ashes with 1 extra player on 1.4.3. Where are you when you have this happen?

**Comment by Xyzcraw** [comment]
I’m not sure where it happed honestly but I did discover a fix for now.  I bought the 3 wolves spirit ash and upgraded it and it restored my ability to use all of them so for now it’s fixed. I’ll try to see if I can recreate it somehow.

**Comment by LukeYui** [comment]
The only parts of the spirit ash system seamless co-op modifies is that it allows you to use them anywhere once per bonfire rest anywhere in the world. 

If you're still unable to use them whilst in a session, then it's likely something your missing (e.g. the spirit bell) or some other restriction that the game has put on your character.

That is to say that the mod never locks spirit ashes when you should be able to use them, it only unlocks them, so I don't see how this could be being caused by the mod.
