### ISSUE TITLE
[Bug]: Can't see dropped weapon that are upgraded

### ISSUE THREAD

**Issue by DemiMort** [LukeYui/EldenRingSeamlessCoopRelease#486]
### Describe the issue in detail

When a player drop an upgraded weapon the other players in the session can't see it on the ground or take it.

### Steps to recreate the bug

1. Upgrade a weapon to +1
2. go to inventory then leave the weapon

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
Hi, this is intentional. You can't see upgraded weapons that exceed your maximum reinforcement level.

For example if 2 players both own maximum upgraded weapons, then they will be able to see whichever upgrade level the other drops. However if you drop a +9 weapon for a player with a maximum upgrade of +8, ,they won't be able to see it.
