### ISSUE TITLE
[Bug]: Stats of me and my duo changed to be unplayable

### ISSUE THREAD

**Issue by Rynesh** [LukeYui/EldenRingSeamlessCoopRelease#527]
### Discord Username

Ryne#5491

### Describe the issue in detail

My damage stat started off going down to 80 for my right armament when it was 130 before I joined coop but I assumed that was due to balance in some way since there are two of us but after switching around the settings to be all wanders are enemies and back between a few of those options to test out with my friends I ended up with 0 armament damage and stats that look like this
![Stats](https://user-images.githubusercontent.com/125709876/219823281-e8f04da8-42fd-4672-8f46-ce3560239084.PNG)

My coop stats were also decreased but it was his health that was decreased.

### Steps to recreate the bug

Switching rules in Judicator's Rulebook.

### Version

1.4.3 (Latest)

**Comment by HarleyDoom** [comment]
Just to clarify, are you familiar with the 'Rot' system that was interduced with the mod that applies one of five different type of debuffs called rot every time you die and can only be cleared by resting at a bonfire? 
Because this looks like the effects of that and you can have rot on you in single player but the effects of the debuff will not apply until you join a co-op session

**Comment by Nymexis** [comment]
Hi ! I'm having the same issue with my friend here.

Whenever I open my world to a wanderer, my stats are going down (damages/health/stamina/mana) and it's the same for my friend which is joining my world.

We've tried resting at bonfires, dying and then resting after leaving, re-joining etc... It didn't change a thing. It only happened to us (that much) when we entered the undergrounds of Leyndell.

**Comment by Nymexis** [comment]
Okay it seems that resting at a bonfire before joining or opening your world for both players makes the problem disappear !
