### ISSUE TITLE
[Bug]: Radahn quest couldn't be activated

### ISSUE THREAD

**Issue by Tonilyn** [LukeYui/EldenRingSeamlessCoopRelease#55]
### Discord Username

OrientWoods#3477

### Describe the issue in detail

One player has already finished game. When this player entered my world (just slayed Rennala), I got Jerren's armor. But upon arrival at the festival at Redmane Castle, Jerren was nowhere to be found. Thus, path to Radahn arena was blocked. Seems like game considers Jerren to be already dead. 
Also, I got steam achievement from the late game stages.

### Steps to recreate the bug

One player should be far ahead in the main questline to join lower level player's world. Then you two go to Redmane Castle where Jerren would normally sit. Lower level player gets Jerren's armour somewhere in Academia it seems. Then, Radahn's arena is blocked as game consideres Jerren to be already defeated according to the higher level player's state of world.  

### Version

1.2.0

**Comment by WesternWolf13** [comment]
I have the same issue. I attempted to use the absolution church, progress other quests that involved jerren, tried several skips, and nothing was able to start the festival. All the npc's were in the plaza but the doors stayed locked to the lift to radahns arena.

**Comment by FallenWolf69** [comment]
### I have had this issue caused by the same scenario and I have a fix. 

If you 'player 1' are trying to defeat Radahn but cannot start the festival because Jerren will not spawn/isn't where he should be, then you must follow these steps:
- Have another player create a new character

- Teleport to the Grace site **Chamber outside the plaza** and let the new player join you

- Have the new character grab the site of grace and leave your game

- New character must open up their world and you can join

- Once in the new characters world, travel to the grace site and Jerren should be waiting for you to start the festival and the door behind the throne should be open, then you can switch over to player 1's world and continue with Radahn

**IF THIS DOESN'T WORK**

- The new character must first clear Margit and Godrick **ON THEIR OWN WORLD** before the festival will be open

If you need any more context or help, feel free to message my discord: Fallen Wolf#6969

**Comment by dotEXCEL** [comment]
didnt work for me, anyone else with another fix?

**Comment by FallenWolf69** [comment]
> 

I see you added me on Discord, I declined it on accident, if you'd like to send it again, I'm happy to help
