### ISSUE TITLE
[Bug]: keep getting inappropriate activity detected and then executable disappears

### ISSUE THREAD

**Issue by krim6** [LukeYui/EldenRingSeamlessCoopRelease#552]
### Discord Username

gang stalking#4978

### Describe the issue in detail

when opening game “inappropriate activity detected” keeps showing up and after a few tries the executable disappears. After this i cannot put a new one in 

### Steps to recreate the bug

i’m not sure

### Version

1.4.5 (Latest)

**Comment by Phil-M-H** [comment]
Same; Elden Ring updated, and doing so deleted `launch_elden_ring_seamlesscoop.exe`

Any attempts to copy it into the /Game/ directory results in it failing due to unknown reasons; even after entering a windows admin password.

I additionally tried to use a bash terminal (launch as administrator) to directly copy the file, and it somehow crashed bash and broke it so thoroughly I can't even restart the bash terminal.

**Comment by LukeYui** [comment]
It sounds like your antivirus program is deleting the launcher. To fix this, you can add an exception for the co-op launcher. 

The source code can be found here if you want to look at it: https://github.com/LukeYui/launch_modded_eldenring

**Comment by krim6** [comment]
> It sounds like your antivirus program is deleting the launcher. To fix this, you can add an exception for the co-op launcher.
> 
> The source code can be found here if you want to look at it: https://github.com/LukeYui/launch_modded_eldenring

im not great with this kinda stuff what would i have to do with the code?

**Comment by krim6** [comment]
it seems to have fixed itself and i can open it again but now i cant join my friends world

**Comment by Eamead** [comment]
Not the Dev but without more information either still your antivirus is blocking the connection or this is a different bug. Did you do what the dev said @krim6 ?
