### ISSUE TITLE
[Bug]: Key item, tool inventory full issue

### ISSUE THREAD

**Issue by Dizis249** [LukeYui/EldenRingSeamlessCoopRelease#68]
### Discord Username

Dizis#6298

### Describe the issue in detail

**Non-host player** started getting error messages often for trying to loot key items and tool items. Even happens with the rot debuff item. (Keep in mind none of these are able to be found in bank).

 _"Unable to acquire [Item Name] this would exceed the maximum able to be held in inventory and storage"_

Also happens when acquiring maps but the map gets revealed nonetheless even if it is not in the inventory at all.

### Steps to recreate the bug

For example, trying to receive important game progression items like the key in Volcano Manor and other quest items like that.

### Version

1.2.1 (Latest)

**Comment by Eisi3erg** [comment]
We had the same issue and had to restart the whole playthrough since key items got lost. Im pretty sure this bug has something to do with the rot debuff spheres. At one point they got stored in my storage chest since my inventory was full for whatever reason. I turned in some quest items to make some space and i could indeed pick some from the storage chest..they showed up in my inventory and i rested at a grace to reset the debuff. They were gone after but my inventory was still full without the rot item showing up. Btw this happend to me only (host) ..my mate had zero issues

**Comment by P4C1F1C4D0R** [comment]
I have the same problem, it does not let me take more objects (from the keys inventory) nor do the disadvantages apply to me

**Comment by MagistrAVSH** [comment]
Same problem. Can't find solution, hope hotfix repairs keys inventory, otherwise save may be considered as broken :(

> Non-host player
Happened with host player.

**Comment by sdj38** [comment]
Same issue here for both host and joining player, Picking up a key item says inventory is full and the item disappears from the game. Noticed it happening after the Rot was being added to the sort chest rather than inventory.

**Comment by LukeYui** [comment]
Fixed in 1.2.2. A fix will be provided for people who's saves have been affected
